/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raffleapp;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class RaffleScreen extends javax.swing.JFrame {
    private String filePath;
    private RaffleApp raffle;

    public RaffleScreen() {
        
        initComponents();     
        raffle = new RaffleApp();
        fileNameLabel.setText("Choose a file...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fileNameLabel = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        drawRaffleButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        winnersTextArea = new javax.swing.JTextArea();
        numberOfDrawText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        multiplePrizeButton = new javax.swing.JRadioButton();
        singlePrizeButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));
        jPanel1.setForeground(new java.awt.Color(102, 255, 153));

        fileNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fileNameLabel.setForeground(new java.awt.Color(51, 0, 204));

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        drawRaffleButton.setText("Draw Raffle");
        drawRaffleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawRaffleButtonActionPerformed(evt);
            }
        });

        winnersTextArea.setBackground(new java.awt.Color(204, 204, 204));
        winnersTextArea.setColumns(20);
        winnersTextArea.setRows(5);
        jScrollPane2.setViewportView(winnersTextArea);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Number Of Draw:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RAFFLE APP");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonGroup1.add(multiplePrizeButton);
        multiplePrizeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        multiplePrizeButton.setText("One person can win more than one prize");
        multiplePrizeButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup1.add(singlePrizeButton);
        singlePrizeButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        singlePrizeButton.setText("One person can only win one prize");
        singlePrizeButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(browseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberOfDrawText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(drawRaffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(multiplePrizeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(singlePrizeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(drawRaffleButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numberOfDrawText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(multiplePrizeButton)
                .addGap(18, 18, 18)
                .addComponent(singlePrizeButton)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        Integer option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            filePath = fileChooser.getSelectedFile().getPath();
                String[] fileP = filePath.split("\\\\");//write only the file name not the whole file path,split according to the back slash character
            fileNameLabel.setText(fileP[fileP.length-1]);
        }
        else{
            
        }

            
    }//GEN-LAST:event_browseButtonActionPerformed

    void writeAttendeesToFile(ArrayList<Attendee> attendees){
        for (Attendee attendee : attendees) {
            try(BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))){
                writer.write(attendee.getName()+","+attendee.getPrizeNumber() + "\n");               
            

            } catch (IOException ex) {
                Logger.getLogger(RaffleScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    private boolean checkStringFormat(String string){
        if(string.contains(",")){
            try{
                Integer ticketNumber = Integer.valueOf(string.split(",")[1]);
                return true;
                
            }catch(java.lang.NumberFormatException e){ // If its not an integer throws an exception therefore the format is not correct
                return false;
            }
        }
        else if(string.split(",").length > 2)//If there are more than one commas
            return false;

        
        return false;
    }

    private void drawRaffleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawRaffleButtonActionPerformed
        if(this.fileNameLabel.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Choose a file");
        }
        else{

            try(Scanner reader = new Scanner(new BufferedReader(new FileReader(filePath)))){
                while((reader.hasNextLine())){
                    String line = reader.nextLine();
                    if(checkStringFormat(line)){
                        String[] arr = line.split(",");
                        String name = arr[0];
                        Integer tickets = Integer.valueOf( arr[1] );                    
                        raffle.createAttendee(name, tickets);
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Invalid file format detected, arrange each line of your file "
                                + "according to the following format:\n"
                                + "Attendee Name,Number Of Ticket" );
                        return;
                    }
                }            

            } catch (IOException ex) { 
               Logger.getLogger(RaffleScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            Integer numberOfDraw = 0;
            try{                
                numberOfDraw = Integer.valueOf( numberOfDrawText.getText());

            }catch(java.lang.NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Invalid Input Format");
            }
            
            if(numberOfDraw > 0){
                String message;
                if(multiplePrizeButton.isSelected()){

                    raffle.drawRaffleMultiplePrize(numberOfDraw);
                    ArrayList<Attendee> winners = raffle.getWinners();
                    winnersTextArea.setText("");
                    message = "";
                    for (Attendee winner : winners) {
                        for (int i = 0; i < winner.getPrizeNumber(); i++) {
                            message += winner.getName() + "\n";                        
                        }
                    }
                    winnersTextArea.setText(message);
                    //clap();// optional clap sound
                    raffle.getAttendees().clear();
                    raffle.getNamePool().clear();
                    raffle.getWinners().clear();
                }
                
                else if (singlePrizeButton.isSelected()){
                    if(numberOfDraw <= raffle.getAttendees().size()){

                        raffle.drawRaffleSinglePrize(numberOfDraw);
                        ArrayList<Attendee> winners = raffle.getWinners();
                        winnersTextArea.setText("");
                        message = "";
                        for (Attendee winner : winners) {
                            message += winner.getName() + "\n";                        

                        }
                        winnersTextArea.setText(message);
                        //clap();//optional clap sound                  

                        raffle.getAttendees().clear();
                        raffle.getNamePool().clear();
                        raffle.getWinners().clear();
                        
                    }
                    else
                        JOptionPane.showMessageDialog(this,"Number of Winners can not be greater than the number of attendees in this option...");
                        
                }
                else{
                    JOptionPane.showMessageDialog(this,"Please Select one of the options..");
                }
            }
            else if (numberOfDraw < 0){
                JOptionPane.showMessageDialog(this,"Number Must Be Positive!");
            }

            
        }            
    }//GEN-LAST:event_drawRaffleButtonActionPerformed
    void clap(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("clap.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(stream);
            clip.start();
            
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(RaffleScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RaffleScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(RaffleScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaffleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaffleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaffleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaffleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaffleScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton drawRaffleButton;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton multiplePrizeButton;
    private javax.swing.JTextField numberOfDrawText;
    private javax.swing.JRadioButton singlePrizeButton;
    private javax.swing.JTextArea winnersTextArea;
    // End of variables declaration//GEN-END:variables
}